# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16bUsO8pSUTfpm8KiW_5nSp7eYthEXl0M
"""

import streamlit as st
import pandas as pd
from transformers import pipeline
import evaluate

st.set_page_config(
    page_title="Netflix Movie Review Sentiment Analysis",
    page_icon="🎬",
    layout="wide"
)

st.markdown("""
<style>
.main{
    background-color:#0E1117;
}
h1,h2,h3{
    color:#E50914;
}
.stButton>button{
    background:#E50914;
    color:white;
    border-radius:10px;
}
</style>
""", unsafe_allow_html=True)

st.title("🎬 Netflix Movie Review Sentiment Analysis")
st.write("Analyze movie reviews using Hugging Face Transformers.")

@st.cache_resource
def load_model():
    classifier = pipeline(
        "sentiment-analysis",
        model="distilbert-base-uncased-finetuned-sst-2-english"
    )
    return classifier

classifier = load_model()

tab1, tab2 = st.tabs(["🔍 Analyze Review", "📊 Evaluate Dataset"])

with tab1:

    review = st.text_area(
        "Enter Movie Review",
        height=180,
        placeholder="Type your movie review here..."
    )

    if st.button("Analyze Sentiment"):

        if review.strip():

            result = classifier(review)[0]

            sentiment = result["label"]
            confidence = result["score"]

            if sentiment == "POSITIVE":
                st.success("😊 Positive Review")
            else:
                st.error("☹️ Negative Review")

            st.metric("Confidence", f"{confidence*100:.2f}%")

            st.progress(float(confidence))

        else:
            st.warning("Please enter a review.")

with tab2:

    uploaded_file = st.file_uploader(
        "Upload CSV File",
        type=["csv"]
    )

    if uploaded_file is not None:

        df = pd.read_csv(uploaded_file, delimiter=";")

        reviews = df["Review"].tolist()
        labels = df["Class"].tolist()

        predictions = classifier(reviews)

        predicted = [x["label"] for x in predictions]

        accuracy = evaluate.load("accuracy")
        f1 = evaluate.load("f1")

        refs = [1 if x=="POSITIVE" else 0 for x in labels]
        preds = [1 if x=="POSITIVE" else 0 for x in predicted]

        acc = accuracy.compute(
            references=refs,
            predictions=preds
        )["accuracy"]

        f1score = f1.compute(
            references=refs,
            predictions=preds
        )["f1"]

        c1,c2 = st.columns(2)

        c1.metric("Accuracy",f"{acc:.3f}")
        c2.metric("F1 Score",f"{f1score:.3f}")

        output = pd.DataFrame({
            "Review":reviews,
            "Actual":labels,
            "Predicted":predicted
        })

        st.dataframe(output,use_container_width=True)

